server:
  port: 0
  
spring:
  application:
    name: user-service
  
# Service Discovery (Eureka)
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    prefer-ip-address: true
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
