server:
  port: 8081
  servlet:
    context-path: /api/auth

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/hotel_auth_db?useSSL=false&serverTimezone=UTC
    username: root
    password: ${AUTH_DB_PASSWORD}
  redis:
    host: redis
    port: 6379
