server:
  port: 8083
  servlet:
    context-path: /api/order

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/orderDB?useSSL=false&serverTimezone=UTC
    username: root
    password: ${ORDER_DB_PASSWORD}
  redis:
    host: redis
    port: 6379
