server:
  port: 8082
  servlet:
    context-path: /api/user

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/userDB?useSSL=false&serverTimezone=UTC
    username: root
    password: ${USER_DB_PASSWORD}
  redis:
    host: redis
    port: 6379
