server:
  port: 8083
  servlet:
    context-path: /api/orders
  
spring:
  application:
    name: order-service
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://config-server:8888"


  level:
    root: INFO
    org:
      springframework: INFO
      springframework.cloud: INFO
    com:
      netflix:
        eureka: INFO
        discovery: INFO