# application.yml
server:
  port: 8083  # host port when running locally

spring:
  application:
    name: order-service

# Eureka Discovery (Local)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
