package com.notification.entity;

public enum ActivityType {

    // Basic Actions
    REGISTER,
    LOGIN,
    LOGOUT,
    ORDER,
    PAYMENT,
    REVIEW,
    PROFILE_UPDATE,

    // Change Actions
    PASSWORD_CHANGE,
    EMAIL_CHANGE,
    PHONE_CHANGE,
    ADDRESS_CHANGE,

    // Reset / Verification Base Actions
    PASSWORD_RESET,
    EMAIL_VERIFICATION,
    PHONE_VERIFICATION,
    ADDRESS_VERIFICATION,

    // Success Status
    PASSWORD_RESET_SUCCESS,
    EMAIL_VERIFICATION_SUCCESS,
    PHONE_VERIFICATION_SUCCESS,
    ADDRESS_VERIFICATION_SUCCESS,

    // Failure Status
    PASSWORD_RESET_FAILURE,
    EMAIL_VERIFICATION_FAILURE,
    PHONE_VERIFICATION_FAILURE,
    ADDRESS_VERIFICATION_FAILURE,

    // Pending Status
    PASSWORD_RESET_PENDING,
    EMAIL_VERIFICATION_PENDING,
    PHONE_VERIFICATION_PENDING,
    ADDRESS_VERIFICATION_PENDING,

    // Cancelled Status
    PASSWORD_RESET_CANCELLED,
    EMAIL_VERIFICATION_CANCELLED,
    PHONE_VERIFICATION_CANCELLED,
    ADDRESS_VERIFICATION_CANCELLED,

    // Expired Status
    PASSWORD_RESET_EXPIRED,
    EMAIL_VERIFICATION_EXPIRED,
    PHONE_VERIFICATION_EXPIRED,
    ADDRESS_VERIFICATION_EXPIRED
}