server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        composite:
          - type: native
            search-locations: classpath:/config

management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    config:
      server:
        composite:
          - type: native
            search-locations: classpath:/config

---
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    config:
      server:
        composite:
          - type: native
            search-locations: classpath:/config



