jwt:
  secret: dG9wU2VjdXJlS2V5Rm9ySFRUUFN5c3RlbTEyMzQ1Ng==
  expiration: 86400000  # 24H

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  info:
    env:
      enabled: true

# logging:
#   level:
#     root: INFO
#     org:
#       springframework: INFO
#       springframework.cloud: INFO
#     com:
#       netflix:
#         eureka: INFO
#         discovery: INFO


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG
    com.gateway: DEBUG  # your package with JwtAuthFilter
