# Config Server application.yml

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  info:
    env:
      enabled: true

logging:
  level:
    root: INFO
    org:
      springframework: INFO
      springframework.cloud: INFO
    com:
      netflix:
        eureka: INFO
        discovery: INFO
