# Config server : discovery-server-dev.yml
server:
  port: 8761

spring:
  application:
    name: discovery-server
  cloud:
    config:
      fail-fast: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost          # or your server IP
    prefer-ip-address: true
  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0
    response-cache-update-interval-ms: 5000

 

 