# Config server : discovery-server-dev.yml
server:
  port: 8761

spring:
  application:
    name: discovery-server


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0
    response-cache-update-interval-ms: 5000

# Let the server start even if Config Server is not yet available
spring:
  cloud:
    config:
      fail-fast: false

 