 
server:
  port: 8083
  servlet:
    context-path: /orders

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://mysql-order:3306/hotel_management_db_order?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Shakib@40
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: mySecretKey12345678901234567890123456789012345678901234567890

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}
 