server:
  port: 8083
  servlet:
    context-path: /orders

spring:
  application:
    name: order-service

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}
